all: assignment0a assignment0b

assignment0a: assignment0a.c
	gcc assignment0a.c -o assignment0a

assignment0b: assignment0b.c
	gcc assignment0b.c -o assignment0b

clean:
	rm -f assignment0a assignment0b
